### PR TITLE
Backport NIO 2's `RequestResponseHandler` to replace `QueueHandler`

### PR DESCRIPTION
**Pull request by Mordil**

### CODE REVIEW

**Comment by Mordil** [comment]
@tanner0101 Given that Vapor 4 is still just past the horizon right now - I figured I'd put in the time to get this up for V3 users to take advantage of immediately.

**Comment by ericchapman** [comment]
@Mordil All of my tests passed no problem with this update.  Thumbs up from me

**Comment by vzsg** [comment]
The pubsub test seems to be nondeterministic, as it failed once yet succeeded on a rerun. I think this improvement is massive enough to not block merging and tagging it just because of that.

**Comment by penny-coin** [comment]
Hey @Mordil, you just merged a pull request, have a coin! 

You now have 97 coins.

**Pull request merged**
