### PR TITLE
Correct RediStack URL and match Vapor's minimum Swift version

### PR DESCRIPTION
**Pull request by gwynne**
Switches to the now-official GitHub URL for RediStack and raises the Swift minimum version to 5.6 to match Vapor.

(Swift version update requires minor version bump.)

### CODE REVIEW

**Review by Joannis — CHANGES_REQUESTED** [review]
Just the docs link that I can see

**Review by 0xTim — CHANGES_REQUESTED** [review]
We should update the exports as part of this PR as well

**Comment by gwynne** [comment]
@0xTim Done, along with the URL in the DocC bundle.

**Review by 0xTim — APPROVED** [review]

**Comment by 0xTim** [comment]
@gwynne we need to either remove the old releases, actually release it (we could take the opportunity to remove exports etc) or fix the release bit, this should be a real release

**Pull request merged**
