### PR TITLE
Add support for Int and Bool conversion from String

### PR DESCRIPTION
**Pull request by collinhundley**
`toInt()` and `toBool()` methods attempt to convert from `simple string` and `bulk string` when necessary.

See #32

### CODE REVIEW

**Comment by czechboy0** [comment]
Please resolve conflicts, then I'll merge ;)

**Comment by collinhundley** [comment]
Oh, I didn't realize my new commits would get added to this PR. I'll get it fixed asap :)

**Comment by czechboy0** [comment]
🔔 😊

**Comment by tanner0101** [comment]
Fixed in #56

**Pull request closed without merging**
