### PR TITLE
Support Vapor 2

### PR DESCRIPTION
**Pull request by johnbona**

### CODE REVIEW

**Comment by johnbona** [comment]
Build is failing due to the performance test:

```
/home/ubuntu/redis/Tests/RedisTests/LiveTests.swift:83: Test Case 'LiveTests.testPerformance' measured [Time, seconds] average: 3.294, relative standard deviation: 13.708%, values: [3.160007, 3.160780, 3.148253, 3.147794, 3.141338, 3.148667, 3.141440, 3.149945, 3.162584, 4.578894], performanceMetricID:org.swift.XCTPerformanceMetric_WallClockTime, maxPercentRelativeStandardDeviation: 10.000%, maxStandardDeviation: 0.100
/home/ubuntu/redis/Tests/RedisTests/LiveTests.swift:83: error: LiveTests.testPerformance : failed: The relative standard deviation of the measurements is 13.708% which is higher than the max allowed of 10.000%.
Test Case 'LiveTests.testPerformance' failed (32.943 seconds)
```

**Comment by tanner0101** [comment]
Thanks!

**Comment by johnbona** [comment]
@tanner0101 No problem! Will you be tagging the repo as 2.0 or going to wait for #63?

**Comment by tanner0101** [comment]
Tagged :)

**Pull request merged**
