### PR TITLE
Keyed cache supporting

### LINKED ISSUE #98: Redis Setup
Currently there is no way to setup Redis with a Keyed Session because that requires access to the `RedisClient`, which we don't have during the setup.

From the Slack:

> Ideally the keyed cache would take either a Future<Connection> to redis, or a connection pool

### PR DESCRIPTION
**Pull request by pedantix**
This PR should provide the support necessary to resolve #98.

### CODE REVIEW

**Comment by pedantix** [comment]
D'OH! totally forgot we added thos to the interface!

**Comment by bre7** [comment]
tanner said he'd take a look next week afaik (both PRs and TLS support)

**Comment by mcdappdev** [comment]
Sweet. Was there a TLS conversation for redis too? I saw the one for postgresql but missed the TLS convo for this

**Comment by bre7** [comment]
I opened #110 when I realized it didn't support tls connections.

**Comment by mcdappdev** [comment]
Oh sweet, good to know!

**Comment by penny-coin** [comment]
Hey @pedantix, you just merged a pull request, have a coin! 

You now have 1 coins.

**Pull request merged**
